Yatube/Yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),

]

Yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    
    path('', views.index, name ='index'),
    path('posts/<slug:slug>/', views.group_posts, name='group_list'),
]

Yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title
    

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

Yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import HttpResponse

from .models import Group, Post


def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 


def group_posts(request, slug):
    template = 'posts /group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = Group.__str__
    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)



 

Yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% load static %}
 <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/logo.png'%}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      <!-- Это тег шаблонизатора include, сюда будет включён код
      из файла includes/header.html -->
      {% include 'includes/header.html' %}
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
    </header>
    <main>
      {% block content %}
      Контент не подвезли :(
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer>
      {% include 'includes/footer.html' %}   
    </footer>
  </body>

Yatube/templates/includes/footer.html
  <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

Yatube/templates/includes/header.html
{% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="index.html">
        <img src="{% static 'img/logo.png'%}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
  </nav>      
    
    


    

Yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества Лев Толстой – зеркало русской революции.
{% endblock %} 
{% block content %}
{% for post in posts %}
      <div class="container">
        <h1>Лев Толстой – зеркало русской революции.</h1>
        <p>
          Группа тайных поклонников графа.
        </p>
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
            {{ post.text }}
        </article>
        <hr>
        <article>
          <ul>
            <li>
        </article>
        <!-- под последним постом нет линии -->
      </div> 
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %} 

Yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последнее обновление
{% endblock %} 
{% block content %}
{% for post in posts %}
      <div class="container py-5">     
        <h1></h1>
        <article>
          <ul>
            <li>
              Автор:{{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
          {{ post.text }}  
          </p>
          {%if post.group.slug is not None %}
           <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {%endif%}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %} 